[unstable]
build-std = ["core"]
#build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nrf5340"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "info,nrf70=trace"
