[unstable]
build-std = ["core"]
#build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs-cli run --chip nrf5340 --allow-erase-all"

[build]
target = "thumbv8m.main-none-eabi"

[env]
DEFMT_LOG = "info"
